{% set name = "signxml" %}
{% set version = "2.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3b78b57e374d5517b4eddbbb27519208ccfbedbcabcf47ee322161f53482f174

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - asn1crypto >=0.24.0
    - certifi >=2018.1.18
    - cryptography >=2.1.4
    - eight >=0.4.2
    - lxml >=4.2.1
    - pyopenssl >=17.5.0
    - python

test:
  imports:
    - signxml
    - signxml.util

about:
  home: https://github.com/kislyuk/signxml
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://signxml.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/signxml

extra:
  recipe-maintainers:
    - fhoehle
