{% set name = "signxml" %}
{% set version = "2.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b70e151d10d99cbc74a50a3344f508ee481fe3c376d61cd1cae850912d303d19

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - asn1crypto >=0.24.0
    - certifi >=2018.1.18
    - cryptography >=2.1.4
    - eight >=0.4.2
    - lxml >=4.2.1
    - pyopenssl >=17.5.0
    - python >=2.7

test:
  imports:
    - signxml
    - signxml.util

about:
  home: https://github.com/kislyuk/signxml
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Python XML Signature library
  doc_url: https://signxml.readthedocs.io/en/latest/
  dev_url: https://github.com/kislyuk/signxml

extra:
  recipe-maintainers:
    - fhoehle
